import { ApiProperty } from '@nestjs/swagger';
import { IsISO8601, IsNotEmpty, IsString } from 'class-validator';

export class CreateReadingDto {
  @ApiProperty({ description: 'UUID generated by the Edge relay, used as the idempotency key' })
  @IsString()
  @IsNotEmpty()
  reading_id: string;

  @ApiProperty({ example: 'door_contact' })
  @IsString()
  @IsNotEmpty()
  sensor_type: string;

  @ApiProperty({ description: 'Sensor reading payload', example: { state: 'open' } })
  @IsNotEmpty()
  value: unknown;

  @ApiProperty({ description: 'ISO8601 timestamp of when the reading was recorded at the edge' })
  @IsISO8601()
  recorded_at: string;
}
